package sqlite

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS agents (
		id TEXT PRIMARY KEY,
		node_id TEXT NOT NULL,
		name TEXT NOT NULL DEFAULT '',
		version TEXT NOT NULL DEFAULT '',
		address TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'unknown',
		capabilities_json TEXT NOT NULL DEFAULT '[]',
		runtime_capabilities_json TEXT NOT NULL DEFAULT '{}',
		metadata_json TEXT NOT NULL DEFAULT '{}',
		registered_at TEXT NOT NULL DEFAULT '',
		last_heartbeat_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT ''
	);`,
	`CREATE INDEX IF NOT EXISTS idx_agents_node_id ON agents(node_id);`,
	`CREATE TABLE IF NOT EXISTS nodes (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL DEFAULT '',
		description TEXT NOT NULL DEFAULT '',
		role TEXT NOT NULL DEFAULT '',
		type TEXT NOT NULL DEFAULT '',
		host TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'unknown',
		classification TEXT NOT NULL DEFAULT 'unknown',
		capability_tier TEXT NOT NULL DEFAULT 'unknown',
		capability_source TEXT NOT NULL DEFAULT 'unknown',
		agent_status TEXT NOT NULL DEFAULT 'none',
		metadata_json TEXT NOT NULL DEFAULT '{}',
		last_seen_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT ''
	);`,
	`CREATE TABLE IF NOT EXISTS runtimes (
		id TEXT PRIMARY KEY,
		node_id TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT '',
		endpoint TEXT NOT NULL DEFAULT '',
		enabled INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'unknown',
		capability_source TEXT NOT NULL DEFAULT 'unknown',
		capabilities_json TEXT NOT NULL DEFAULT '[]',
		actions_json TEXT NOT NULL DEFAULT '[]',
		last_seen_at TEXT NOT NULL DEFAULT '',
		metadata_json TEXT NOT NULL DEFAULT '{}',
		updated_at TEXT NOT NULL DEFAULT '',
		FOREIGN KEY(node_id) REFERENCES nodes(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_runtimes_node_id ON runtimes(node_id);`,
	`CREATE TABLE IF NOT EXISTS models (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL DEFAULT '',
		display_name TEXT NOT NULL DEFAULT '',
		model_type TEXT NOT NULL DEFAULT 'unknown',
		source_type TEXT NOT NULL DEFAULT 'unknown',
		model_format TEXT NOT NULL DEFAULT 'unknown',
		path_or_ref TEXT NOT NULL DEFAULT '',
		size_bytes INTEGER NOT NULL DEFAULT 0,
		default_args_json TEXT NOT NULL DEFAULT '{}',
		requires_script INTEGER NOT NULL DEFAULT 0,
		script_ref TEXT NOT NULL DEFAULT '',
		tags_json TEXT NOT NULL DEFAULT '[]',
		provider TEXT NOT NULL DEFAULT '',
		backend_type TEXT NOT NULL DEFAULT '',
		host_node_id TEXT NOT NULL DEFAULT '',
		runtime_id TEXT NOT NULL DEFAULT '',
		endpoint TEXT NOT NULL DEFAULT '',
		state TEXT NOT NULL DEFAULT 'unknown',
		desired_state TEXT NOT NULL DEFAULT 'unknown',
		observed_state TEXT NOT NULL DEFAULT 'unknown',
		readiness TEXT NOT NULL DEFAULT 'unknown',
		health_message TEXT NOT NULL DEFAULT '',
		last_reconciled_at TEXT NOT NULL DEFAULT '',
		context_length INTEGER NOT NULL DEFAULT 0,
		metadata_json TEXT NOT NULL DEFAULT '{}',
		updated_at TEXT NOT NULL DEFAULT ''
	);`,
	`CREATE INDEX IF NOT EXISTS idx_models_host_node_id ON models(host_node_id);`,
	`CREATE TABLE IF NOT EXISTS runtime_bindings (
		id TEXT PRIMARY KEY,
		model_id TEXT NOT NULL DEFAULT '',
		template_id TEXT NOT NULL DEFAULT '',
		binding_mode TEXT NOT NULL DEFAULT 'generic_injected',
		node_selector_json TEXT NOT NULL DEFAULT '{}',
		preferred_node TEXT NOT NULL DEFAULT '',
		mount_rules_json TEXT NOT NULL DEFAULT '[]',
		env_overrides_json TEXT NOT NULL DEFAULT '{}',
		command_override_json TEXT NOT NULL DEFAULT '[]',
		script_ref TEXT NOT NULL DEFAULT '',
		compatibility_status TEXT NOT NULL DEFAULT 'unknown',
		compatibility_message TEXT NOT NULL DEFAULT '',
		enabled INTEGER NOT NULL DEFAULT 1,
		manifest_id TEXT NOT NULL DEFAULT '',
		metadata_json TEXT NOT NULL DEFAULT '{}',
		created_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT '',
		FOREIGN KEY(model_id) REFERENCES models(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_runtime_bindings_model ON runtime_bindings(model_id);`,
	`CREATE INDEX IF NOT EXISTS idx_runtime_bindings_template ON runtime_bindings(template_id);`,
	`CREATE TABLE IF NOT EXISTS runtime_instances (
		id TEXT PRIMARY KEY,
		model_id TEXT NOT NULL DEFAULT '',
		template_id TEXT NOT NULL DEFAULT '',
		binding_id TEXT NOT NULL DEFAULT '',
		node_id TEXT NOT NULL DEFAULT '',
		desired_state TEXT NOT NULL DEFAULT 'unknown',
		observed_state TEXT NOT NULL DEFAULT 'unknown',
		readiness TEXT NOT NULL DEFAULT 'unknown',
		health_message TEXT NOT NULL DEFAULT '',
		drift_reason TEXT NOT NULL DEFAULT '',
		endpoint TEXT NOT NULL DEFAULT '',
		launched_command_json TEXT NOT NULL DEFAULT '[]',
		mounted_paths_json TEXT NOT NULL DEFAULT '[]',
		injected_env_json TEXT NOT NULL DEFAULT '{}',
		script_used TEXT NOT NULL DEFAULT '',
		last_reconciled_at TEXT NOT NULL DEFAULT '',
		metadata_json TEXT NOT NULL DEFAULT '{}',
		created_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT '',
		FOREIGN KEY(model_id) REFERENCES models(id) ON DELETE CASCADE,
		FOREIGN KEY(binding_id) REFERENCES runtime_bindings(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_runtime_instances_model ON runtime_instances(model_id);`,
	`CREATE INDEX IF NOT EXISTS idx_runtime_instances_binding ON runtime_instances(binding_id);`,
	`CREATE TABLE IF NOT EXISTS runtime_bundle_manifests (
		id TEXT PRIMARY KEY,
		template_id TEXT NOT NULL DEFAULT '',
		manifest_version TEXT NOT NULL DEFAULT '',
		template_type TEXT NOT NULL DEFAULT 'unknown',
		runtime_kind TEXT NOT NULL DEFAULT 'unknown',
		supported_model_types_json TEXT NOT NULL DEFAULT '[]',
		supported_formats_json TEXT NOT NULL DEFAULT '[]',
		capabilities_json TEXT NOT NULL DEFAULT '[]',
		mount_points_json TEXT NOT NULL DEFAULT '[]',
		required_env_json TEXT NOT NULL DEFAULT '[]',
		optional_env_json TEXT NOT NULL DEFAULT '[]',
		command_override_allowed INTEGER NOT NULL DEFAULT 0,
		script_mount_allowed INTEGER NOT NULL DEFAULT 0,
		model_injection_mode TEXT NOT NULL DEFAULT 'generic_injected',
		healthcheck_json TEXT NOT NULL DEFAULT '{}',
		exposed_ports_json TEXT NOT NULL DEFAULT '[]',
		notes TEXT NOT NULL DEFAULT '',
		metadata_json TEXT NOT NULL DEFAULT '{}',
		updated_at TEXT NOT NULL DEFAULT ''
	);`,
	`CREATE INDEX IF NOT EXISTS idx_runtime_bundle_manifests_template ON runtime_bundle_manifests(template_id);`,
	`CREATE TABLE IF NOT EXISTS tasks (
		id TEXT PRIMARY KEY,
		type TEXT NOT NULL DEFAULT '',
		target_type TEXT NOT NULL DEFAULT '',
		target_id TEXT NOT NULL DEFAULT '',
		assigned_agent_id TEXT NOT NULL DEFAULT '',
		worker_id TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'pending',
		progress INTEGER NOT NULL DEFAULT 0,
		message TEXT NOT NULL DEFAULT '',
		detail_json TEXT NOT NULL DEFAULT '{}',
		payload_json TEXT NOT NULL DEFAULT '{}',
		error TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL DEFAULT '',
		accepted_at TEXT NOT NULL DEFAULT '',
		started_at TEXT NOT NULL DEFAULT '',
		finished_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT ''
	);`,
	`CREATE INDEX IF NOT EXISTS idx_tasks_target ON tasks(target_type, target_id, created_at DESC);`,
	`CREATE INDEX IF NOT EXISTS idx_tasks_status_agent ON tasks(status, assigned_agent_id, created_at DESC);`,
	`CREATE TABLE IF NOT EXISTS test_runs (
		id TEXT PRIMARY KEY,
		scenario TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'pending',
		started_at TEXT NOT NULL DEFAULT '',
		finished_at TEXT NOT NULL DEFAULT '',
		log_path TEXT NOT NULL DEFAULT '',
		summary TEXT NOT NULL DEFAULT '',
		triggered_by TEXT NOT NULL DEFAULT '',
		error TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL DEFAULT '',
		updated_at TEXT NOT NULL DEFAULT ''
	);`,
	`CREATE INDEX IF NOT EXISTS idx_test_runs_created_at ON test_runs(created_at DESC);`,
}
